defaults:
  noLogging: make blank to log
  signalfx:
    apiToken: '...'
  pulse:
    username: '...'
    password: '...'
  taskcluster:
    credentials:
      clientId: '...'
      accessToken: '...'
